build.writeStats = true
baseURL = 'https://rcorzon.github.io/'
title = 'Just my stuff'
theme = 'hugo-theme'
defaultContentLanguageInSubdir = true
[languages]
  [languages.es]
    contentDir = 'content/es'
    disabled = false
    languageCode = 'es-Es'
    languageDirection = 'ltr'
    languageName = 'Español'
    title = 'Just my stuff'
    weight = 1
    [languages.es.params]
      #subtitle = 'Referenz, Tutorials und Erklärungen'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Project Documentation'
    weight = 2
    [languages.en.params]
      #subtitle = 'Reference, Tutorials, and Explanations'
[author]
  name = "Rubén Corzón Villar"
  bio = "Full Stack Developer focused on Microsoft technologies. Azure Certified"
  [author.params]
    layout = "custom-layout"
    [author.social]
        github = "rcorzon"
        stackoverflow = "7913036"
        linkedin = "rubencorzon"
[social]
    github = "rcorzon"
    stackoverflow = "7913036"
    linkedin = "rubencorzon"
[Params]
    comment = false
    [Params.post]
        panel = false   # Hiding inferior menu
        copyright = false