build.writeStats = true
baseURL = 'http://example.org/'
#languageCode = 'en-us'
languageCode = 'es-ES'
title = 'Just my stuff'
theme = 'hugo-theme'
[author]
  name = "Rubén Corzón Villar"
  [author.params]
    layout = "custom-layout"
    [author.social]
        github = "rcorzon"
        stackoverflow = "7913036"
        linkedin = "rubencorzon"
[social]
    github = "rcorzon"
    stackoverflow = "7913036"
    linkedin = "rubencorzon"
[Params]
    comment = false
    [Params.post]
        panel = false   # Hiding inferior menu
        copyright = false