build.writeStats = true
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Just my stuff'
theme = 'hugo-theme'
[author]
  name = "Rubén Corzón Villar"
  [author.params]
    layout = "custom-layout"