build.writeStats = true
baseURL = 'https://rcorzon.github.io/'
title = 'Just my stuff'
theme = 'hugo-theme'
defaultContentLanguageInSubdir = true
[languages]
  [languages.es]
    disabled = false
    languageCode = 'es-Es'
    languageDirection = 'ltr'
    languageName = 'Español'
    weight = 1
    [languages.es.author]
      name = "Rubén Corzón Villar"
      bio = "Desarrollador Full Stack en tecnologías de Microsoft. Certificado en Azure"
        [language.es.author.params]
        layout = "custom-layout"
        [languages.es.author.social]
          github = "rcorzon"
          stackoverflow = "7913036"
          linkedin = "rubencorzon"
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2
    [languages.en.author]
      name = "Rubén Corzón Villar"
      bio = "Full Stack Developer focused on Microsoft technologies. Azure Certified"
      [language.en.author.params]
      layout = "custom-layout"
      [languages.en.author.social]
        github = "rcorzon"
        stackoverflow = "7913036"
        linkedin = "rubencorzon"
[social]
    github = "rcorzon"
    stackoverflow = "7913036"
    linkedin = "rubencorzon"
[Params]
    comment = false
    [Params.post]
        panel = false   # Hiding inferior menu
        copyright = false